; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -mattr=+xpulpv -O2 < %s | FileCheck %s

; Guards 20/F003: PULPHardwareLoops must accept a count-down loop whose latch
; compares the decremented counter with zero (BNE %iv.next, $x0) and use the
; original counter register as the lp.setup count, and must turn a loop with
; a constant trip count into lp.setupi. Both used to crash the pass.
; Note: no -verify-machineinstrs yet; PULPFixupHwLoops has a separate,
; pre-existing verifier finding (see xpulp-hwloop.ll).

@sink = dso_local global i32 0, align 4

; do { acc += *p++; } while (--n);
define i32 @countdown(ptr %p, i32 %n) {
; CHECK-LABEL: countdown:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a2, 0
; CHECK-NEXT:    blez a1, .LBB0_3
; CHECK-NEXT:  # %bb.1: # %loop.preheader
; CHECK-NEXT:    lp.setup x0, a1, .LBB0_4
; CHECK-NEXT:  .LBB0_2: # Block address taken
; CHECK-NEXT:    # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    p.lw a3, 4(a0!)
; CHECK-NEXT:  .LBB0_4: # in Loop: Header=BB0_2 Depth=1
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    add a2, a2, a3
; CHECK-NEXT:  .LBB0_3: # %exit
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
; CHECK-NEXT:  .Ltmp0: # Address of block that was removed by CodeGen
entry:
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %loop, label %exit

loop:
  %i = phi i32 [ %n, %entry ], [ %i.next, %loop ]
  %ptr = phi ptr [ %p, %entry ], [ %ptr.next, %loop ]
  %acc = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  %v = load i32, ptr %ptr
  %acc.next = add i32 %acc, %v
  %ptr.next = getelementptr i8, ptr %ptr, i32 4
  %i.next = add nsw i32 %i, -1
  %done = icmp eq i32 %i.next, 0
  br i1 %done, label %exit, label %loop

exit:
  %r = phi i32 [ 0, %entry ], [ %acc.next, %loop ]
  ret i32 %r
}

; for (int i = 0; i < 31; i++) { x = x * 3 + (y >> 5); y ^= x; } sink = 31;
define i32 @single31(i32 %x, i32 %y) {
; CHECK-LABEL: single31:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a3, 31
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  # %bb.4: # %entry
; CHECK-NEXT:    lp.setupi x0, 31, .LBB1_3
; CHECK-NEXT:  .LBB1_1: # Block address taken
; CHECK-NEXT:    # %for.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    mv a2, a1
; CHECK-NEXT:    slli a1, a0, 1
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:    srli a1, a2, 5
; CHECK-NEXT:    add a0, a1, a0
; CHECK-NEXT:  .LBB1_3: # in Loop: Header=BB1_1 Depth=1
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    xor a1, a0, a2
; CHECK-NEXT:  # %bb.2: # %for.cond.cleanup
; CHECK-NEXT:    lui a0, %hi(sink)
; CHECK-NEXT:    li a1, 31
; CHECK-NEXT:    sw a1, %lo(sink)(a0)
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
; CHECK-NEXT:  .Ltmp1: # Address of block that was removed by CodeGen
entry:
  br label %for.body

for.cond.cleanup:
  store volatile i32 31, ptr @sink, align 4
  ret i32 %y.addr.010

for.body:
  %i.012 = phi i32 [ 0, %entry ], [ %inc1, %for.body ]
  %y.addr.010 = phi i32 [ %y, %entry ], [ %xor, %for.body ]
  %x.addr.09 = phi i32 [ %x, %entry ], [ %add, %for.body ]
  %mul = mul i32 %x.addr.09, 3
  %shr = lshr i32 %y.addr.010, 5
  %add = add i32 %shr, %mul
  %xor = xor i32 %add, %y.addr.010
  %inc1 = add nuw nsw i32 %i.012, 1
  %exitcond.not = icmp eq i32 %inc1, 31
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
