; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O3 -mtriple=riscv32 -mattr=+m,+c,+zfinx,+xpulpv < %s | FileCheck %s

; Guards 20/F005: PULPFixupHwLoops must handle loop layouts produced by block
; placement and tail duplication without crashing and without moving the
; hardware-loop end away from the latch:
;  - latch_above_header: the latch is laid out above the header and the loop
;    sits at the end of the function (reduced from GAP9 KerParMatMulDSP_Fix16);
;  - empty_latch: the latch holds only the compare and branch;
;  - seed22_taildup: tail duplication gives the loop a second back edge, so no
;    hardware loop may be formed (hwloop fuzzer seed 22).
; The lp.setup must be directly followed by the loop header, and the lp end
; label must sit on the latch's last instruction.

define void @latch_above_header(i32 %0, i1 %cmp55898.not, i1 %exitcond.not) {
; CHECK-LABEL: latch_above_header:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andi a1, a1, 1
; CHECK-NEXT:  .LBB0_1: # %for.body23
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    beqz a1, .LBB0_1
; CHECK-NEXT:  # %bb.2: # %for.cond53.preheader
; CHECK-NEXT:    beqz a1, .LBB0_4
; CHECK-NEXT:  .LBB0_3: # %for.inc359
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB0_4: # %for.body56.preheader
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  # %bb.9: # %for.body56.preheader
; CHECK-NEXT:    lp.setup x0, a0, .LBB0_8
; CHECK-NEXT:  .LBB0_6: # %for.body56
; CHECK-NEXT:    # =>This Loop Header: Depth=1
; CHECK-NEXT:    # Child Loop BB0_7 Depth 2
; CHECK-NEXT:    bnez a2, .LBB0_5
; CHECK-NEXT:  .LBB0_7: # %for.body69
; CHECK-NEXT:    # Parent Loop BB0_6 Depth=1
; CHECK-NEXT:    # => This Inner Loop Header: Depth=2
; CHECK-NEXT:    beqz a1, .LBB0_7
; CHECK-NEXT:  .LBB0_5: # Block address taken
; CHECK-NEXT:    # %if.end176
; CHECK-NEXT:    # in Loop: Header=BB0_6 Depth=1
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:  .LBB0_8: # in Loop: Header=BB0_6 Depth=1
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    addi a3, a3, 1
; CHECK-NEXT:    j .LBB0_3
; CHECK-NEXT:  .Ltmp0: # Address of block that was removed by CodeGen
entry:
  br label %for.body23

for.cond53.preheader:                             ; preds = %for.body23
  br i1 %cmp55898.not, label %for.inc359, label %for.body56

for.body23:                                       ; preds = %for.body23, %entry
  br i1 %cmp55898.not, label %for.cond53.preheader, label %for.body23

for.body56:                                       ; preds = %if.end176, %for.cond53.preheader
  %Line.0899 = phi i32 [ %inc244, %if.end176 ], [ 0, %for.cond53.preheader ]
  br i1 %exitcond.not, label %if.end176, label %for.body69

for.body69:                                       ; preds = %for.body69, %for.body56
  br i1 %cmp55898.not, label %if.end176, label %for.body69

if.end176:                                        ; preds = %for.body69, %for.body56
  %inc244 = add i32 %Line.0899, 1
  %exitcond988.not = icmp eq i32 %inc244, %0
  br i1 %exitcond988.not, label %for.inc359, label %for.body56

for.inc359:                                       ; preds = %if.end176, %for.cond53.preheader
  ret void
}

define i32 @empty_latch(ptr %invariant.gep, i1 %tobool154.not) {
; CHECK-LABEL: empty_latch:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addi a2, a0, 4
; CHECK-NEXT:    sub a3, a2, a0
; CHECK-NEXT:    srli a3, a3, 2
; CHECK-NEXT:    andi a1, a1, 1
; CHECK-NEXT:    .p2align 2
; CHECK-NEXT:  # %bb.5: # %entry
; CHECK-NEXT:    lp.setup x0, a3, .LBB1_4
; CHECK-NEXT:  .LBB1_1: # %for.body133
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    p.lw zero, 4(a0!)
; CHECK-NEXT:  .LBB1_2: # Block address taken
; CHECK-NEXT:    # %for.inc161
; CHECK-NEXT:    # in Loop: Header=BB1_1 Depth=1
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:  .LBB1_4: # in Loop: Header=BB1_1 Depth=1
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    nop
; CHECK-NEXT:  # %bb.3: # %for.cond165.preheader
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:  .Ltmp1: # Address of block that was removed by CodeGen
entry:
  br label %for.body133

for.cond165.preheader:                            ; preds = %for.inc161
  ret i32 0

for.body133:                                      ; preds = %for.inc161, %entry
  %i1128.0317 = phi i32 [ 0, %entry ], [ %inc162, %for.inc161 ]
  %gep = getelementptr i32, ptr %invariant.gep, i32 %i1128.0317
  %0 = load i32, ptr %gep, align 4
  br i1 %tobool154.not, label %for.inc161, label %if.then155

if.then155:                                       ; preds = %for.body133
  %add159 = or i32 0, %0
  br label %for.inc161

for.inc161:                                       ; preds = %if.then155, %for.body133
  %inc162 = add i32 %i1128.0317, 1
  %exitcond335.not = icmp eq i32 %i1128.0317, 0
  br i1 %exitcond335.not, label %for.cond165.preheader, label %for.body133
}

define i32 @seed22_taildup(ptr nocapture noundef readonly %A, ptr nocapture noundef readonly %B, ptr nocapture noundef writeonly %out, i32 noundef %n, i32 noundef %m, i32 noundef %k) {
; CHECK-LABEL: seed22_taildup:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    beqz a3, .LBB2_7
; CHECK-NEXT:  # %bb.1: # %for.body.lr.ph
; CHECK-NEXT:    addi a7, a3, 44
; CHECK-NEXT:    li a4, 44
; CHECK-NEXT:    sub a6, a7, a4
; CHECK-NEXT:    li a5, 3
; CHECK-NEXT:    j .LBB2_4
; CHECK-NEXT:  .LBB2_2: # %if.else
; CHECK-NEXT:    # in Loop: Header=BB2_4 Depth=1
; CHECK-NEXT:    slli a5, a5, 1
; CHECK-NEXT:  .LBB2_3: # Block address taken
; CHECK-NEXT:    # %if.end
; CHECK-NEXT:    # in Loop: Header=BB2_4 Depth=1
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    addi a4, a4, 1
; CHECK-NEXT:    slli a5, a5, 1
; CHECK-NEXT:    beq a4, a7, .LBB2_6
; CHECK-NEXT:  .LBB2_4: # %for.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    andi a3, a4, 63
; CHECK-NEXT:    slli a3, a3, 2
; CHECK-NEXT:    add a3, a3, a1
; CHECK-NEXT:    lbu a3, 0(a3)
; CHECK-NEXT:    andi a3, a3, 1
; CHECK-NEXT:    beqz a3, .LBB2_2
; CHECK-NEXT:  # %bb.5: # %if.then
; CHECK-NEXT:    # in Loop: Header=BB2_4 Depth=1
; CHECK-NEXT:    addi a3, a5, 6
; CHECK-NEXT:    lw a6, 164(a0)
; CHECK-NEXT:    andi a3, a3, 63
; CHECK-NEXT:    slli a3, a3, 2
; CHECK-NEXT:    add a3, a3, a1
; CHECK-NEXT:    lw t0, 96(a1)
; CHECK-NEXT:    lw a3, 0(a3)
; CHECK-NEXT:    add a6, a6, t0
; CHECK-NEXT:    add a6, a6, a3
; CHECK-NEXT:    slli a3, a6, 3
; CHECK-NEXT:    sub a3, a3, a6
; CHECK-NEXT:    sw a3, 32(a2)
; CHECK-NEXT:    addi a4, a4, 1
; CHECK-NEXT:    slli a5, a5, 1
; CHECK-NEXT:    bne a4, a7, .LBB2_4
; CHECK-NEXT:  .LBB2_6: # %for.cond.cleanup.loopexit
; CHECK-NEXT:    xori a0, a5, 3
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB2_7:
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    ret
; CHECK-NEXT:  .Ltmp2: # Address of block that was removed by CodeGen
entry:
  %cmp32.not = icmp eq i32 %n, 0
  br i1 %cmp32.not, label %for.cond.cleanup, label %for.body.lr.ph

for.body.lr.ph:                                   ; preds = %entry
  %arrayidx7 = getelementptr inbounds nuw i8, ptr %A, i32 164
  %arrayidx10 = getelementptr inbounds nuw i8, ptr %B, i32 96
  %arrayidx15 = getelementptr inbounds nuw i8, ptr %out, i32 32
  br label %for.body

for.cond.cleanup.loopexit:                        ; preds = %if.end
  %0 = xor i32 %shl16, 3
  br label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond.cleanup.loopexit, %entry
  %t.0.lcssa = phi i32 [ 0, %entry ], [ %0, %for.cond.cleanup.loopexit ]
  ret i32 %t.0.lcssa

for.body:                                         ; preds = %for.body.lr.ph, %if.end
  %i0.034 = phi i32 [ 0, %for.body.lr.ph ], [ %inc, %if.end ]
  %t.033 = phi i32 [ 3, %for.body.lr.ph ], [ %shl16, %if.end ]
  %add = add i32 %i0.034, 44
  %and = and i32 %add, 63
  %arrayidx = getelementptr inbounds nuw i32, ptr %B, i32 %and
  %1 = load i32, ptr %arrayidx, align 4
  %and1 = and i32 %1, 1
  %tobool.not = icmp eq i32 %and1, 0
  br i1 %tobool.not, label %if.else, label %if.then

if.then:                                          ; preds = %for.body
  %add2 = add i32 %t.033, 6
  %and3 = and i32 %add2, 63
  %arrayidx4 = getelementptr inbounds nuw i32, ptr %B, i32 %and3
  %2 = load i32, ptr %arrayidx4, align 4
  %3 = load i32, ptr %arrayidx7, align 4
  %4 = load i32, ptr %arrayidx10, align 4
  %add11 = add i32 %3, %2
  %add12 = add i32 %add11, %4
  %mul = mul i32 %add12, 7
  store i32 %mul, ptr %arrayidx15, align 4
  br label %if.end

if.else:                                          ; preds = %for.body
  %shl = shl i32 %t.033, 1
  br label %if.end

if.end:                                           ; preds = %if.else, %if.then
  %t.1 = phi i32 [ %t.033, %if.then ], [ %shl, %if.else ]
  %shl16 = shl i32 %t.1, 1
  %inc = add nuw i32 %i0.034, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup.loopexit, label %for.body
}
