; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -mattr=+m,+xpulpv,+zfinx < %s \
; RUN:   | FileCheck %s --check-prefix=ZFINX
; RUN: llc -mtriple=riscv32 -mattr=+m,+xpulpv,+f < %s \
; RUN:   | FileCheck %s --check-prefix=F

; Guards 20/F006: with Xpulpv2 and Zfinx (floats in integer registers) a float
; load in a loop is a post-increment p.lw (immediate stride: p.lw rd, 4(rs!);
; register stride: p.lw rd, rs2(rs!)), as for an int load and as GAP9 GCC does.
; Float stores deliberately stay a plain sw (F006 note: p.sw would stop
; hardware-loop formation). With the F extension (floats in F registers) p.lw
; cannot be used, so no p.lw may appear.
; No -verify-machineinstrs on these full-pipeline RUN lines: PULPFixupHwLoops
; has a separate, pre-existing verifier finding (see xpulp-hwloop.ll); the
; verifier-checked view of the same functions is xpulp-postinc-f32-mir.ll.

define float @dot(ptr nocapture noundef readonly %a, ptr nocapture noundef readonly %b, i32 noundef %n) {
; ZFINX-LABEL: dot:
; ZFINX:       # %bb.0: # %entry
; ZFINX-NEXT:    blez a2, .LBB0_4
; ZFINX-NEXT:  # %bb.1: # %for.body.preheader
; ZFINX-NEXT:    slli a2, a2, 2
; ZFINX-NEXT:    add a3, a1, a2
; ZFINX-NEXT:    sub a2, a3, a1
; ZFINX-NEXT:    srli a4, a2, 2
; ZFINX-NEXT:    li a2, 0
; ZFINX-NEXT:    .p2align 2
; ZFINX-NEXT:  # %bb.6: # %for.body.preheader
; ZFINX-NEXT:    lp.setup x0, a4, .LBB0_5
; ZFINX-NEXT:  .LBB0_2: # Block address taken
; ZFINX-NEXT:    # %for.body
; ZFINX-NEXT:    # =>This Inner Loop Header: Depth=1
; ZFINX-NEXT:    # Label of block must be emitted
; ZFINX-NEXT:    p.lw a4, 4(a0!)
; ZFINX-NEXT:    p.lw a5, 4(a1!)
; ZFINX-NEXT:  .LBB0_5: # in Loop: Header=BB0_2 Depth=1
; ZFINX-NEXT:    # Label of block must be emitted
; ZFINX-NEXT:    fmadd.s a2, a4, a5, a2
; ZFINX-NEXT:  # %bb.3: # %for.cond.cleanup
; ZFINX-NEXT:    mv a0, a2
; ZFINX-NEXT:    ret
; ZFINX-NEXT:  .LBB0_4:
; ZFINX-NEXT:    li a0, 0
; ZFINX-NEXT:    ret
; ZFINX-NEXT:  .Ltmp0: # Address of block that was removed by CodeGen
;
; F-LABEL: dot:
; F:       # %bb.0: # %entry
; F-NEXT:    blez a2, .LBB0_4
; F-NEXT:  # %bb.1: # %for.body.preheader
; F-NEXT:    slli a2, a2, 2
; F-NEXT:    add a2, a1, a2
; F-NEXT:    sub a3, a2, a1
; F-NEXT:    srli a3, a3, 2
; F-NEXT:    fmv.w.x fa0, zero
; F-NEXT:    .p2align 2
; F-NEXT:  # %bb.6: # %for.body.preheader
; F-NEXT:    lp.setup x0, a3, .LBB0_5
; F-NEXT:  .LBB0_2: # Block address taken
; F-NEXT:    # %for.body
; F-NEXT:    # =>This Inner Loop Header: Depth=1
; F-NEXT:    # Label of block must be emitted
; F-NEXT:    flw fa5, 0(a0)
; F-NEXT:    flw fa4, 0(a1)
; F-NEXT:    addi a1, a1, 4
; F-NEXT:    fmadd.s fa0, fa5, fa4, fa0
; F-NEXT:  .LBB0_5: # in Loop: Header=BB0_2 Depth=1
; F-NEXT:    # Label of block must be emitted
; F-NEXT:    addi a0, a0, 4
; F-NEXT:  # %bb.3: # %for.cond.cleanup
; F-NEXT:    ret
; F-NEXT:  .LBB0_4:
; F-NEXT:    fmv.w.x fa0, zero
; F-NEXT:    ret
; F-NEXT:  .Ltmp0: # Address of block that was removed by CodeGen
entry:
  %cmp6 = icmp sgt i32 %n, 0
  br i1 %cmp6, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.body, %entry
  %s.0.lcssa = phi float [ 0.000000e+00, %entry ], [ %2, %for.body ]
  ret float %s.0.lcssa

for.body:                                         ; preds = %entry, %for.body
  %i.08 = phi i32 [ %inc, %for.body ], [ 0, %entry ]
  %s.07 = phi float [ %2, %for.body ], [ 0.000000e+00, %entry ]
  %arrayidx = getelementptr inbounds nuw float, ptr %a, i32 %i.08
  %0 = load float, ptr %arrayidx, align 4
  %arrayidx1 = getelementptr inbounds nuw float, ptr %b, i32 %i.08
  %1 = load float, ptr %arrayidx1, align 4
  %2 = tail call float @llvm.fmuladd.f32(float %0, float %1, float %s.07)
  %inc = add nuw nsw i32 %i.08, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define float @dot_stride(ptr nocapture noundef readonly %a, i32 noundef %stride, i32 noundef %n) {
; ZFINX-LABEL: dot_stride:
; ZFINX:       # %bb.0: # %entry
; ZFINX-NEXT:    li a3, 0
; ZFINX-NEXT:    blez a2, .LBB1_3
; ZFINX-NEXT:  # %bb.1: # %for.body.preheader
; ZFINX-NEXT:    slli a1, a1, 2
; ZFINX-NEXT:    .p2align 2
; ZFINX-NEXT:  # %bb.5: # %for.body.preheader
; ZFINX-NEXT:    lp.setup x0, a2, .LBB1_4
; ZFINX-NEXT:  .LBB1_2: # Block address taken
; ZFINX-NEXT:    # %for.body
; ZFINX-NEXT:    # =>This Inner Loop Header: Depth=1
; ZFINX-NEXT:    # Label of block must be emitted
; ZFINX-NEXT:    p.lw a4, a1(a0!)
; ZFINX-NEXT:  .LBB1_4: # in Loop: Header=BB1_2 Depth=1
; ZFINX-NEXT:    # Label of block must be emitted
; ZFINX-NEXT:    fadd.s a3, a3, a4
; ZFINX-NEXT:  .LBB1_3: # %for.cond.cleanup
; ZFINX-NEXT:    mv a0, a3
; ZFINX-NEXT:    ret
; ZFINX-NEXT:  .Ltmp1: # Address of block that was removed by CodeGen
;
; F-LABEL: dot_stride:
; F:       # %bb.0: # %entry
; F-NEXT:    blez a2, .LBB1_4
; F-NEXT:  # %bb.1: # %for.body.preheader
; F-NEXT:    slli a1, a1, 2
; F-NEXT:    fmv.w.x fa0, zero
; F-NEXT:    .p2align 2
; F-NEXT:  # %bb.6: # %for.body.preheader
; F-NEXT:    lp.setup x0, a2, .LBB1_5
; F-NEXT:  .LBB1_2: # Block address taken
; F-NEXT:    # %for.body
; F-NEXT:    # =>This Inner Loop Header: Depth=1
; F-NEXT:    # Label of block must be emitted
; F-NEXT:    flw fa5, 0(a0)
; F-NEXT:    fadd.s fa0, fa0, fa5
; F-NEXT:  .LBB1_5: # in Loop: Header=BB1_2 Depth=1
; F-NEXT:    # Label of block must be emitted
; F-NEXT:    add a0, a0, a1
; F-NEXT:  # %bb.3: # %for.cond.cleanup
; F-NEXT:    ret
; F-NEXT:  .LBB1_4:
; F-NEXT:    fmv.w.x fa0, zero
; F-NEXT:    ret
; F-NEXT:  .Ltmp1: # Address of block that was removed by CodeGen
entry:
  %cmp4 = icmp sgt i32 %n, 0
  br i1 %cmp4, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.body, %entry
  %s.0.lcssa = phi float [ 0.000000e+00, %entry ], [ %add, %for.body ]
  ret float %s.0.lcssa

for.body:                                         ; preds = %entry, %for.body
  %i.07 = phi i32 [ %inc, %for.body ], [ 0, %entry ]
  %s.06 = phi float [ %add, %for.body ], [ 0.000000e+00, %entry ]
  %a.addr.05 = phi ptr [ %add.ptr, %for.body ], [ %a, %entry ]
  %0 = load float, ptr %a.addr.05, align 4
  %add = fadd float %s.06, %0
  %add.ptr = getelementptr inbounds float, ptr %a.addr.05, i32 %stride
  %inc = add nuw nsw i32 %i.07, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @scale_store(ptr nocapture noundef writeonly %o, float noundef %k, i32 noundef %n) {
; ZFINX-LABEL: scale_store:
; ZFINX:       # %bb.0: # %entry
; ZFINX-NEXT:    blez a2, .LBB2_3
; ZFINX-NEXT:  # %bb.1: # %for.body.preheader
; ZFINX-NEXT:    slli a2, a2, 2
; ZFINX-NEXT:    add a2, a0, a2
; ZFINX-NEXT:    sub a3, a2, a0
; ZFINX-NEXT:    srli a4, a3, 2
; ZFINX-NEXT:    li a3, 0
; ZFINX-NEXT:    .p2align 2
; ZFINX-NEXT:  # %bb.5: # %for.body.preheader
; ZFINX-NEXT:    lp.setup x0, a4, .LBB2_4
; ZFINX-NEXT:  .LBB2_2: # Block address taken
; ZFINX-NEXT:    # %for.body
; ZFINX-NEXT:    # =>This Inner Loop Header: Depth=1
; ZFINX-NEXT:    # Label of block must be emitted
; ZFINX-NEXT:    fcvt.s.wu a4, a3
; ZFINX-NEXT:    fmul.s a4, a1, a4
; ZFINX-NEXT:    sw a4, 0(a0)
; ZFINX-NEXT:    addi a0, a0, 4
; ZFINX-NEXT:  .LBB2_4: # in Loop: Header=BB2_2 Depth=1
; ZFINX-NEXT:    # Label of block must be emitted
; ZFINX-NEXT:    addi a3, a3, 1
; ZFINX-NEXT:  .LBB2_3: # %for.cond.cleanup
; ZFINX-NEXT:    ret
; ZFINX-NEXT:  .Ltmp2: # Address of block that was removed by CodeGen
;
; F-LABEL: scale_store:
; F:       # %bb.0: # %entry
; F-NEXT:    blez a1, .LBB2_3
; F-NEXT:  # %bb.1: # %for.body.preheader
; F-NEXT:    slli a1, a1, 2
; F-NEXT:    add a1, a0, a1
; F-NEXT:    sub a2, a1, a0
; F-NEXT:    srli a3, a2, 2
; F-NEXT:    li a2, 0
; F-NEXT:    .p2align 2
; F-NEXT:  # %bb.5: # %for.body.preheader
; F-NEXT:    lp.setup x0, a3, .LBB2_4
; F-NEXT:  .LBB2_2: # Block address taken
; F-NEXT:    # %for.body
; F-NEXT:    # =>This Inner Loop Header: Depth=1
; F-NEXT:    # Label of block must be emitted
; F-NEXT:    fcvt.s.wu fa5, a2
; F-NEXT:    fmul.s fa5, fa0, fa5
; F-NEXT:    fsw fa5, 0(a0)
; F-NEXT:    addi a0, a0, 4
; F-NEXT:  .LBB2_4: # in Loop: Header=BB2_2 Depth=1
; F-NEXT:    # Label of block must be emitted
; F-NEXT:    addi a2, a2, 1
; F-NEXT:  .LBB2_3: # %for.cond.cleanup
; F-NEXT:    ret
; F-NEXT:  .Ltmp2: # Address of block that was removed by CodeGen
entry:
  %cmp4 = icmp sgt i32 %n, 0
  br i1 %cmp4, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ %inc, %for.body ], [ 0, %entry ]
  %conv = uitofp nneg i32 %i.05 to float
  %mul = fmul float %k, %conv
  %arrayidx = getelementptr inbounds nuw float, ptr %o, i32 %i.05
  store float %mul, ptr %arrayidx, align 4
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
