; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -mattr=+xpulpv -verify-machineinstrs < %s | FileCheck %s

; Guards 20/F002: the immediate of p.clip/p.clipu is the bit width derived from
; the bounds (clip to [-2^(i-1), 2^(i-1)-1], clipu to [0, 2^(i-1)-1]), and the
; first immediate of p.extract/p.extractu is size-1 (GAP9 GCC and the ISA
; encoding), so __builtin_pulp_bextract(x, 8, 8) extracts 8 bits, not 9.

declare i32 @llvm.riscv.pulp.clip(i32, i32, i32)
declare i32 @llvm.riscv.pulp.clipu(i32, i32, i32)
declare i32 @llvm.riscv.pulp.bextract(i32, i32, i32)
declare i32 @llvm.riscv.pulp.bextractu(i32, i32, i32)

define i32 @clip_i8(i32 %x) {
; CHECK-LABEL: clip_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    p.clip a0, a0, 8
; CHECK-NEXT:    ret
  %r = call i32 @llvm.riscv.pulp.clip(i32 %x, i32 -128, i32 127)
  ret i32 %r
}

define i32 @clip_i16(i32 %x) {
; CHECK-LABEL: clip_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    p.clip a0, a0, 16
; CHECK-NEXT:    ret
  %r = call i32 @llvm.riscv.pulp.clip(i32 %x, i32 -32768, i32 32767)
  ret i32 %r
}

define i32 @clip_i1(i32 %x) {
; CHECK-LABEL: clip_i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    p.clip a0, a0, 1
; CHECK-NEXT:    ret
  %r = call i32 @llvm.riscv.pulp.clip(i32 %x, i32 -1, i32 0)
  ret i32 %r
}

define i32 @clipu_u8(i32 %x) {
; CHECK-LABEL: clipu_u8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    p.clipu a0, a0, 9
; CHECK-NEXT:    ret
  %r = call i32 @llvm.riscv.pulp.clipu(i32 %x, i32 0, i32 255)
  ret i32 %r
}

define i32 @extract_8_8(i32 %x) {
; CHECK-LABEL: extract_8_8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    p.extract a0, a0, 7, 8
; CHECK-NEXT:    ret
  %r = call i32 @llvm.riscv.pulp.bextract(i32 %x, i32 8, i32 8)
  ret i32 %r
}

define i32 @extractu_8_8(i32 %x) {
; CHECK-LABEL: extractu_8_8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    p.extractu a0, a0, 7, 8
; CHECK-NEXT:    ret
  %r = call i32 @llvm.riscv.pulp.bextractu(i32 %x, i32 8, i32 8)
  ret i32 %r
}

define i32 @extractu_32_0(i32 %x) {
; CHECK-LABEL: extractu_32_0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    p.extractu a0, a0, 31, 0
; CHECK-NEXT:    ret
  %r = call i32 @llvm.riscv.pulp.bextractu(i32 %x, i32 32, i32 0)
  ret i32 %r
}
