; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -O3 -mtriple=riscv32 -mattr=+m,+xpulpv -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; Guards 20/E007: RISCVTTIImpl::getPreferredAddressingMode returns
; AMK_PostIndexed for Xpulpv2, so Loop Strength Reduction keeps the second
; pointer as its own induction variable and ISel folds its increment into a
; post-increment load (p.lbu rd, 1(rs!)). This is the Xpulpv2 counterpart of
; upstream's xcvmem-heuristic.ll (f590963db836); the IR is the same.
; Without the preference LSR rewrites the second pointer as %b + %e + i and
; the load leaves the loop as a plain lbu.

define i32 @test_heuristic(ptr %b, i32 %e, i1 %0) {
; CHECK-LABEL: test_heuristic:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    add a3, a0, a1
; CHECK-NEXT:    andi a2, a2, 1
; CHECK-NEXT:  .LBB0_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    p.lbu a1, 1(a3!)
; CHECK-NEXT:    addi a0, a0, 1
; CHECK-NEXT:    beqz a2, .LBB0_1
; CHECK-NEXT:  # %bb.2: # %exit
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:    ret
entry:
  %1 = getelementptr i8, ptr %b, i32 %e
  br label %loop

loop:                                             ; preds = %loop, %entry
  %2 = phi ptr [ %b, %entry ], [ %7, %loop ]
  %3 = phi ptr [ %1, %entry ], [ %8, %loop ]
  %4 = load i8, ptr %2, align 1
  %5 = load i8, ptr %3, align 1
  %6 = zext i8 %5 to i32
  %7 = getelementptr i8, ptr %2, i32 1
  %8 = getelementptr i8, ptr %3, i32 1
  br i1 %0, label %exit, label %loop

exit:                                             ; preds = %loop
  ret i32 %6
}
