; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -mtriple=riscv32 -mattr=+xpulpv,+zfinx -passes="print<cost-model>" \
; RUN:   -disable-output 2>&1 | FileCheck %s --check-prefix=THRU
; RUN: opt < %s -mtriple=riscv32 -mattr=+xpulpv,+zfinx -passes="print<cost-model>" \
; RUN:   -cost-kind=code-size -disable-output 2>&1 | FileCheck %s --check-prefix=SIZE

; Guards 20/F004: Xpulpv2 makes <2 x i16> and <4 x i8> legal in integer
; registers, without the V extension. Cost queries on these types (memory ops,
; insert/extract element, shuffles, build vectors) must not take the RVV-only
; path, which asserted "Tried to get vector length without Zve or V extension
; support!" (at -O3 via SimpleLoopUnswitch on GAP9 FIR/MatMul DSP kernels).
; Lives in CodeGen/RISCV rather than Analysis/CostModel/RISCV so that the port
; harness's lit suite (config.env LIT_PATHS) runs it.

define void @mem(ptr %p, ptr %q) {
; THRU-LABEL: 'mem'
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %a = load <2 x i16>, ptr %p, align 4
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %b = load <4 x i8>, ptr %q, align 4
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store <2 x i16> %a, ptr %q, align 4
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store <4 x i8> %b, ptr %p, align 4
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %c = load <2 x i16>, ptr %p, align 2
; THRU-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: store <2 x i16> <i16 1, i16 2>, ptr %q, align 4
; THRU-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SIZE-LABEL: 'mem'
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %a = load <2 x i16>, ptr %p, align 4
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %b = load <4 x i8>, ptr %q, align 4
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store <2 x i16> %a, ptr %q, align 4
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: store <4 x i8> %b, ptr %p, align 4
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %c = load <2 x i16>, ptr %p, align 2
; SIZE-NEXT:  Cost Model: Found an estimated cost of 4 for instruction: store <2 x i16> <i16 1, i16 2>, ptr %q, align 4
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
  %a = load <2 x i16>, ptr %p, align 4
  %b = load <4 x i8>, ptr %q, align 4
  store <2 x i16> %a, ptr %q, align 4
  store <4 x i8> %b, ptr %p, align 4
  %c = load <2 x i16>, ptr %p, align 2
  store <2 x i16> <i16 1, i16 2>, ptr %q, align 4
  ret void
}

define void @arith(<2 x i16> %a, <2 x i16> %b, <4 x i8> %c, <4 x i8> %d) {
; THRU-LABEL: 'arith'
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %1 = add <2 x i16> %a, %b
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %2 = sub <4 x i8> %c, %d
; THRU-NEXT:  Cost Model: Found an estimated cost of 5 for instruction: %3 = mul <2 x i16> %a, %b
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %4 = and <4 x i8> %c, %d
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %5 = shl <2 x i16> %a, %b
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %6 = call <2 x i16> @llvm.smax.v2i16(<2 x i16> %a, <2 x i16> %b)
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %7 = call <4 x i8> @llvm.abs.v4i8(<4 x i8> %c, i1 false)
; THRU-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SIZE-LABEL: 'arith'
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %1 = add <2 x i16> %a, %b
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %2 = sub <4 x i8> %c, %d
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %3 = mul <2 x i16> %a, %b
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %4 = and <4 x i8> %c, %d
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %5 = shl <2 x i16> %a, %b
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %6 = call <2 x i16> @llvm.smax.v2i16(<2 x i16> %a, <2 x i16> %b)
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %7 = call <4 x i8> @llvm.abs.v4i8(<4 x i8> %c, i1 false)
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
  %1 = add <2 x i16> %a, %b
  %2 = sub <4 x i8> %c, %d
  %3 = mul <2 x i16> %a, %b
  %4 = and <4 x i8> %c, %d
  %5 = shl <2 x i16> %a, %b
  %6 = call <2 x i16> @llvm.smax.v2i16(<2 x i16> %a, <2 x i16> %b)
  %7 = call <4 x i8> @llvm.abs.v4i8(<4 x i8> %c, i1 false)
  ret void
}

define void @misc(<2 x i16> %a, <2 x i16> %b, <4 x i8> %c, i16 %s) {
; THRU-LABEL: 'misc'
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %e = extractelement <2 x i16> %a, i32 1
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %i = insertelement <2 x i16> %a, i16 %s, i32 0
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %sh = shufflevector <2 x i16> %a, <2 x i16> %b, <2 x i32> <i32 1, i32 2>
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %sp = shufflevector <2 x i16> %i, <2 x i16> poison, <2 x i32> zeroinitializer
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %cmp = icmp slt <2 x i16> %a, %b
; THRU-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %sel = select <2 x i1> %cmp, <2 x i16> %a, <2 x i16> %b
; THRU-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %sx = sext <4 x i8> %c to <4 x i16>
; THRU-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: %tr = trunc <2 x i16> %a to <2 x i8>
; THRU-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %bc = bitcast <2 x i16> %a to i32
; THRU-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %r = call i16 @llvm.vector.reduce.add.v2i16(<2 x i16> %a)
; THRU-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: ret void
;
; SIZE-LABEL: 'misc'
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %e = extractelement <2 x i16> %a, i32 1
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %i = insertelement <2 x i16> %a, i16 %s, i32 0
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %sh = shufflevector <2 x i16> %a, <2 x i16> %b, <2 x i32> <i32 1, i32 2>
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %sp = shufflevector <2 x i16> %i, <2 x i16> poison, <2 x i32> zeroinitializer
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %cmp = icmp slt <2 x i16> %a, %b
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %sel = select <2 x i1> %cmp, <2 x i16> %a, <2 x i16> %b
; SIZE-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %sx = sext <4 x i8> %c to <4 x i16>
; SIZE-NEXT:  Cost Model: Found an estimated cost of 0 for instruction: %tr = trunc <2 x i16> %a to <2 x i8>
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: %bc = bitcast <2 x i16> %a to i32
; SIZE-NEXT:  Cost Model: Found an estimated cost of 3 for instruction: %r = call i16 @llvm.vector.reduce.add.v2i16(<2 x i16> %a)
; SIZE-NEXT:  Cost Model: Found an estimated cost of 1 for instruction: ret void
;
  %e = extractelement <2 x i16> %a, i32 1
  %i = insertelement <2 x i16> %a, i16 %s, i32 0
  %sh = shufflevector <2 x i16> %a, <2 x i16> %b, <2 x i32> <i32 1, i32 2>
  %sp = shufflevector <2 x i16> %i, <2 x i16> poison, <2 x i32> zeroinitializer
  %cmp = icmp slt <2 x i16> %a, %b
  %sel = select <2 x i1> %cmp, <2 x i16> %a, <2 x i16> %b
  %sx = sext <4 x i8> %c to <4 x i16>
  %tr = trunc <2 x i16> %a to <2 x i8>
  %bc = bitcast <2 x i16> %a to i32
  %r = call i16 @llvm.vector.reduce.add.v2i16(<2 x i16> %a)
  ret void
}
declare <2 x i16> @llvm.smax.v2i16(<2 x i16>, <2 x i16>)
declare <4 x i8> @llvm.abs.v4i8(<4 x i8>, i1)
declare i16 @llvm.vector.reduce.add.v2i16(<2 x i16>)
