; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -mattr=+m,+xpulpv,+zfinx -verify-machineinstrs \
; RUN:   -stop-before=pulp-hwloops < %s | FileCheck %s

; Guards 20/F006 at the machine-instruction level, with the machine verifier
; on: a Zfinx f32 post-increment load is P_LW_ri_PostIncrement (immediate
; stride) or P_LW_rr_PostIncrement (register stride), the opcodes the PULP
; hardware-loop pass recognises as the pointer update, and its GPR result
; reaches the float user (FMADD_S_INX / FADD_S_INX) as the GPRF32
; sub-register. The float store stays a plain SW_INX.
; The assembly view of the same functions is in xpulp-postinc-f32.ll.

define float @dot(ptr nocapture noundef readonly %a, ptr nocapture noundef readonly %b, i32 noundef %n) {
  ; CHECK-LABEL: name: dot
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.4(0x30000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   BLT [[COPY3]], [[COPY]], %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gprf32 = COPY $x0_w
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.for.body.preheader:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY]], 2
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[COPY1]], killed [[SLLI]]
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gprf32 = COPY $x0_w
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.for.cond.cleanup:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprf32 = PHI [[COPY4]], %bb.4, %5, %bb.3
  ; CHECK-NEXT:   $x10_w = COPY [[PHI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10_w
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.for.body:
  ; CHECK-NEXT:   successors: %bb.2(0x04000000), %bb.3(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr = PHI [[COPY2]], %bb.1, %7, %bb.3
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gpr = PHI [[COPY1]], %bb.1, %6, %bb.3
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:gprf32 = PHI [[COPY5]], %bb.1, %5, %bb.3
  ; CHECK-NEXT:   [[P_LW_ri_PostIncrement:%[0-9]+]]:gpr, [[P_LW_ri_PostIncrement1:%[0-9]+]]:gpr = P_LW_ri_PostIncrement [[PHI1]], 4
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gprf32 = COPY [[P_LW_ri_PostIncrement]].sub_32
  ; CHECK-NEXT:   [[P_LW_ri_PostIncrement2:%[0-9]+]]:gpr, [[P_LW_ri_PostIncrement3:%[0-9]+]]:gpr = P_LW_ri_PostIncrement [[PHI2]], 4
  ; CHECK-NEXT:   [[COPY7:%[0-9]+]]:gprf32 = COPY [[P_LW_ri_PostIncrement2]].sub_32
  ; CHECK-NEXT:   [[FMADD_S_INX:%[0-9]+]]:gprf32 = nofpexcept FMADD_S_INX killed [[COPY6]], killed [[COPY7]], [[PHI3]], 7, implicit $frm
  ; CHECK-NEXT:   BEQ [[P_LW_ri_PostIncrement3]], [[ADD]], %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.3
entry:
  %cmp6 = icmp sgt i32 %n, 0
  br i1 %cmp6, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.body, %entry
  %s.0.lcssa = phi float [ 0.000000e+00, %entry ], [ %2, %for.body ]
  ret float %s.0.lcssa

for.body:                                         ; preds = %entry, %for.body
  %i.08 = phi i32 [ %inc, %for.body ], [ 0, %entry ]
  %s.07 = phi float [ %2, %for.body ], [ 0.000000e+00, %entry ]
  %arrayidx = getelementptr inbounds nuw float, ptr %a, i32 %i.08
  %0 = load float, ptr %arrayidx, align 4
  %arrayidx1 = getelementptr inbounds nuw float, ptr %b, i32 %i.08
  %1 = load float, ptr %arrayidx1, align 4
  %2 = tail call float @llvm.fmuladd.f32(float %0, float %1, float %s.07)
  %inc = add nuw nsw i32 %i.08, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
define float @dot_stride(ptr nocapture noundef readonly %a, i32 noundef %stride, i32 noundef %n) {
  ; CHECK-LABEL: name: dot_stride
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.4(0x30000000)
  ; CHECK-NEXT:   liveins: $x10, $x11, $x12
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gpr = COPY $x11
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   BLT [[COPY3]], [[COPY]], %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gprf32 = COPY $x0_w
  ; CHECK-NEXT:   PseudoBR %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.for.body.preheader:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY1]], 2
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gprf32 = COPY $x0_w
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.for.cond.cleanup:
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gprf32 = PHI [[COPY4]], %bb.4, %5, %bb.3
  ; CHECK-NEXT:   $x10_w = COPY [[PHI]]
  ; CHECK-NEXT:   PseudoRET implicit $x10_w
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.for.body:
  ; CHECK-NEXT:   successors: %bb.2(0x04000000), %bb.3(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr = PHI [[COPY2]], %bb.1, %7, %bb.3
  ; CHECK-NEXT:   [[PHI2:%[0-9]+]]:gpr = PHI [[COPY]], %bb.1, %6, %bb.3
  ; CHECK-NEXT:   [[PHI3:%[0-9]+]]:gprf32 = PHI [[COPY5]], %bb.1, %5, %bb.3
  ; CHECK-NEXT:   [[P_LW_rr_PostIncrement:%[0-9]+]]:gpr, [[P_LW_rr_PostIncrement1:%[0-9]+]]:gpr = P_LW_rr_PostIncrement [[PHI1]], [[SLLI]]
  ; CHECK-NEXT:   [[COPY6:%[0-9]+]]:gprf32 = COPY [[P_LW_rr_PostIncrement]].sub_32
  ; CHECK-NEXT:   [[FADD_S_INX:%[0-9]+]]:gprf32 = nofpexcept FADD_S_INX [[PHI3]], killed [[COPY6]], 7, implicit $frm
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = ADDI [[PHI2]], -1
  ; CHECK-NEXT:   BEQ [[ADDI]], $x0, %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.3
entry:
  %cmp4 = icmp sgt i32 %n, 0
  br i1 %cmp4, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.body, %entry
  %s.0.lcssa = phi float [ 0.000000e+00, %entry ], [ %add, %for.body ]
  ret float %s.0.lcssa

for.body:                                         ; preds = %entry, %for.body
  %i.07 = phi i32 [ %inc, %for.body ], [ 0, %entry ]
  %s.06 = phi float [ %add, %for.body ], [ 0.000000e+00, %entry ]
  %a.addr.05 = phi ptr [ %add.ptr, %for.body ], [ %a, %entry ]
  %0 = load float, ptr %a.addr.05, align 4
  %add = fadd float %s.06, %0
  %add.ptr = getelementptr inbounds float, ptr %a.addr.05, i32 %stride
  %inc = add nuw nsw i32 %i.07, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
define void @scale_store(ptr nocapture noundef writeonly %o, float noundef %k, i32 noundef %n) {
  ; CHECK-LABEL: name: scale_store
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x50000000), %bb.2(0x30000000)
  ; CHECK-NEXT:   liveins: $x10, $x12, $x11_w
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gpr = COPY $x12
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gprf32 = COPY $x11_w
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:gpr = COPY $x10
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   BGE [[COPY3]], [[COPY]], %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.for.body.preheader:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[SLLI:%[0-9]+]]:gpr = SLLI [[COPY]], 2
  ; CHECK-NEXT:   [[ADD:%[0-9]+]]:gpr = ADD [[COPY2]], killed [[SLLI]]
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:gpr = COPY $x0
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:gpr = COPY [[COPY4]]
  ; CHECK-NEXT:   PseudoBR %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.for.cond.cleanup:
  ; CHECK-NEXT:   PseudoRET
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3.for.body:
  ; CHECK-NEXT:   successors: %bb.2(0x04000000), %bb.3(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:gpr = PHI [[COPY2]], %bb.1, %4, %bb.3
  ; CHECK-NEXT:   [[PHI1:%[0-9]+]]:gpr = PHI [[COPY5]], %bb.1, %3, %bb.3
  ; CHECK-NEXT:   [[FCVT_S_WU_INX:%[0-9]+]]:gprf32 = nofpexcept FCVT_S_WU_INX [[PHI1]], 7, implicit $frm
  ; CHECK-NEXT:   [[FMUL_S_INX:%[0-9]+]]:gprf32 = nofpexcept FMUL_S_INX [[COPY1]], killed [[FCVT_S_WU_INX]], 7, implicit $frm
  ; CHECK-NEXT:   SW_INX killed [[FMUL_S_INX]], [[PHI]], 0 :: (store (s32) into %ir.lsr.iv1)
  ; CHECK-NEXT:   [[ADDI:%[0-9]+]]:gpr = nuw nsw ADDI [[PHI1]], 1
  ; CHECK-NEXT:   [[ADDI1:%[0-9]+]]:gpr = ADDI [[PHI]], 4
  ; CHECK-NEXT:   BEQ [[ADDI1]], [[ADD]], %bb.2
  ; CHECK-NEXT:   PseudoBR %bb.3
entry:
  %cmp4 = icmp sgt i32 %n, 0
  br i1 %cmp4, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.body, %entry
  ret void

for.body:                                         ; preds = %entry, %for.body
  %i.05 = phi i32 [ %inc, %for.body ], [ 0, %entry ]
  %conv = uitofp nneg i32 %i.05 to float
  %mul = fmul float %k, %conv
  %arrayidx = getelementptr inbounds nuw float, ptr %o, i32 %i.05
  store float %mul, ptr %arrayidx, align 4
  %inc = add nuw nsw i32 %i.05, 1
  %exitcond.not = icmp eq i32 %inc, %n
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
